apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  namespace: argocd  
spec:
  destination:
    name: default
    namespace: ruby-rails   
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/Rajajodu02/Devops-Project/tree/main/my_docker_file'  
    path: "Manifests"  
    targetRevision: HEAD 
  syncPolicy:
    automated:
      prune: true  # Remove resources not defined in Git
      selfHeal: true  # Automatically recover from sync failures
